### ISSUE TITLE
packet_deframer not found

### ISSUE THREAD

**Issue by AD7ZJ** [tkuester/gr-lacrosse#1]
Edit: sorry, I accidentally put this under gr-lacrosse. The issue is with gr-reveng.

When I try and run the example grc flow graph, I get the following error. 

Traceback (most recent call last):
  File "./reveng_simple_test.py", line 193, in <module>
    main()
  File "./reveng_simple_test.py", line 181, in main
    tb = top_block_cls()
  File "./reveng_simple_test.py", line 74, in __init__
    self.reveng_packet_deframer_0 = reveng.packet_deframer("RevengTestSrc", sync_word_bits, False, 2, 0, 4, 1, False)
AttributeError: 'module' object has no attribute 'packet_deframer'

It seems there is some problem binding to the C packet_deframer function?

**Comment by johnzbesko** [comment]
I got the same error. I'm working on an OrangePi, running Armbian because the gnuradio package is still on version 3.7.#, unlike my Kubuntu desktop running 20.04 Amd64.

**Comment by tkuester** [comment]
Hey everyone, sorry I haven't had a chance to maintain this. I've been awful busy with life and work. I'm hoping to take care of this around Christmas time. Sorry I haven't been responding!

In the mean time, while gr-lacrosse isn't working on 3.8, I have done some work porting gr-reveng to 3.8. If you look at the "maint-3.8" branch, you should see some of the things I did to get it to work. If you can write some code to help me, I'll accept pull requests!

**Comment by johnzbesko** [comment]
Trying to compile reveng, but the following errors crop up:

*******************************

johnz@ZAMD64:~/GRadioC/gr-reveng-maint-3.8$ cmake CMakeLists.txt
-- Build type not specified: defaulting to release.
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY
MPIR_INCLUDE_DIR) 
-- User set python executable /usr/bin/python3
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found
suitable exact version "3.8.5") 
-- Using install prefix: /usr/local
-- Building for version: v1.0-compat-xxx-xunknown / 1.0.0git
-- No C++ unit tests... skipping
-- 
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found
version "3.8.5") 
-- Configuring done
CMake Error in lib/CMakeLists.txt:
  Imported target "gnuradio::gnuradio-runtime" includes non-existent
path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does
not
  provide.

CMake Error in lib/CMakeLists.txt:
  Imported target "gnuradio::gnuradio-runtime" includes non-existent
path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does
not
  provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated
correctly.

**********************************

I have installed all the gnuradio Ubuntu packages, with the exception
of air-modes, DAB and hpsdr.

The "Pattern Dump" module was built and installed properly. The
GnuRadio GUI no longer shows a missing block for the Pattern Dump
module when the temp_mon.grc from gr-lacrosse is loaded.

As for Checking for "module 'mpir >= 3.0'
--   No package 'mpir' found", I do have python3-gmpy2
installed.

Any help is greatly appreciated!

**Comment by johnzbesko** [comment]
OK, got reveng_simple_test.py to work. The reveng python module was
placed into a "wrong" directory. This command fixed it:

sudo cp -R /usr/local/lib/python3/dist-packages/reveng
/usr/local/lib/python3.8/dist-packages/reveng
